/**
 * ROLLOUT Template
 * Renders rollout data to markdown
 */

import type { DocForgeState, Risk } from '../state/types.js';

/**
 * Render the ROLLOUT document from state
 */
export function renderRollout(state: DocForgeState): string {
    const { project, documentProgress } = state;
    const rollout = documentProgress.rollout;

    const sections: string[] = [];

    // Header
    sections.push(`# Rollout Plan: ${project.name}`);
    sections.push('');
    sections.push(`> Generated by DocForge Agents`);
    sections.push('');

    // Risks
    if (rollout.risks && rollout.risks.length > 0) {
        sections.push('## Key Risks');
        sections.push('');
        sections.push(renderRisksTable(rollout.risks));
        sections.push('');
    }

    // Observability
    if (rollout.observability) {
        sections.push('## Observability');
        sections.push('');
        sections.push(rollout.observability);
        sections.push('');
    }

    // Rollout Steps
    if (rollout.rolloutSteps && rollout.rolloutSteps.length > 0) {
        sections.push('## Rollout Steps');
        sections.push('');
        rollout.rolloutSteps.forEach((step, index) => {
            sections.push(`${index + 1}. ${step}`);
        });
        sections.push('');
    }

    // Kill Switch
    if (rollout.killSwitch) {
        sections.push('## Kill Switch');
        sections.push('');
        sections.push(rollout.killSwitch);
        sections.push('');
    }

    // Rollback
    if (rollout.rollback) {
        sections.push('## Rollback Procedure');
        sections.push('');
        sections.push(rollout.rollback);
        sections.push('');
    }

    // Stop Conditions
    if (rollout.stopConditions && rollout.stopConditions.length > 0) {
        sections.push('## Stop-the-Line Conditions');
        sections.push('');
        sections.push('Stop immediately if any of the following occur:');
        sections.push('');
        rollout.stopConditions.forEach(condition => {
            sections.push(`- ⛔ ${condition}`);
        });
        sections.push('');
    }

    return sections.join('\n');
}

/**
 * Render risks as a markdown table
 */
export function renderRisksTable(risks: Risk[]): string {
    const lines: string[] = [];

    lines.push('| Risk | Severity | Mitigation |');
    lines.push('|------|----------|------------|');

    for (const risk of risks) {
        const severityEmoji = getSeverityEmoji(risk.severity);
        lines.push(`| ${risk.description} | ${severityEmoji} ${risk.severity} | ${risk.mitigation} |`);
    }

    return lines.join('\n');
}

/**
 * Get emoji for severity level
 */
function getSeverityEmoji(severity: Risk['severity']): string {
    switch (severity) {
        case 'critical':
            return '🔴';
        case 'high':
            return '🟠';
        case 'medium':
            return '🟡';
        case 'low':
            return '🟢';
        default:
            return '⚪';
    }
}

/**
 * Format risks as markdown sections (alternative to table)
 */
export function formatRisksSections(risks: Risk[]): string {
    return risks
        .map(risk => {
            const severityEmoji = getSeverityEmoji(risk.severity);
            return [
                `### ${severityEmoji} ${risk.description}`,
                '',
                `**Severity:** ${risk.severity}`,
                '',
                `**Mitigation:** ${risk.mitigation}`,
            ].join('\n');
        })
        .join('\n\n');
}
